package ar.org.inclusoft.api.staff;

import java.util.List; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly = true) class StaffMemberService { private final StaffMemberRepository repository; StaffMemberService(StaffMemberRepository repository) { this.repository = repository; }
 List<StaffMemberResponse> findAll(String search) { List<StaffMember> items = search == null || search.isBlank() ? repository.findAllByOrderByFullNameAsc() : repository.findByFullNameContainingIgnoreCaseOrDocumentNumberContainingIgnoreCaseOrProfessionContainingIgnoreCaseOrderByFullNameAsc(search.trim(), search.trim(), search.trim()); return items.stream().map(StaffMemberResponse::from).toList(); }
 @Transactional StaffMemberResponse create(StaffMemberRequest request) { String document = trim(request.documentNumber()); if (document != null && repository.findByDocumentNumber(document).isPresent()) throw new IllegalArgumentException("Ya existe una persona con ese DNI."); return StaffMemberResponse.from(repository.save(new StaffMember(request.fullName().trim(), request.profile(), document, trim(request.phoneNumber()), trim(request.email()), trim(request.profession())))); }
 @Transactional StaffMemberResponse update(UUID id, StaffMemberRequest request) { StaffMember item = find(id); String document = trim(request.documentNumber()); if (document != null && repository.existsByDocumentNumberAndIdNot(document, id)) throw new IllegalArgumentException("Ya existe una persona con ese DNI."); item.update(request.fullName().trim(), request.profile(), document, trim(request.phoneNumber()), trim(request.email()), trim(request.profession())); return StaffMemberResponse.from(item); }
 @Transactional StaffMemberResponse deactivate(UUID id) { StaffMember item = find(id); item.deactivate(); return StaffMemberResponse.from(item); } @Transactional StaffMemberResponse activate(UUID id) { StaffMember item = find(id); item.activate(); return StaffMemberResponse.from(item); }
 private StaffMember find(UUID id) { return repository.findById(id).orElseThrow(() -> new IllegalArgumentException("No se encontró la persona solicitada.")); } private String trim(String value) { return value == null || value.isBlank() ? null : value.trim(); } }
